"""empty message

Revision ID: 4702045e1f03
Revises: b87ee3972001
Create Date: 2024-12-18 14:27:47.616241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4702045e1f03'
down_revision = 'b87ee3972001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('origem_instrumento')
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_fisico', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('natureza_instrumento', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.drop_column('natureza_instrumento')
        batch_op.drop_column('estado_fisico')

    op.create_table('origem_instrumento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estado_fisico', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('natureza_instrumento', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('instrumento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumento.id'], name='origem_instrumento_instrumento_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'instrumento_id', name='origem_instrumento_pkey')
    )
    # ### end Alembic commands ###
