"""empty message

Revision ID: b87ee3972001
Revises: 90bc77a3a8be
Create Date: 2024-12-18 09:26:04.697026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87ee3972001'
down_revision = '90bc77a3a8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toca',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('evento_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cpf'], ['integrante.cpf'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toca')
    # ### end Alembic commands ###
