from .integrante import Integrante
from .endereco import Endereco
from .telefone import Telefone
from .instrumento import Instrumento
from .eventos import Evento
from .equipameto_suporte import EquipamentoSuporte
from .responsavel import Responsavel
from .utiliza import Utiliza
from .toca import Toca